AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example AWS Lambda function that's called via API Gateway

Resources:
  ApiGatewayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: api-gateway-function
      Handler: lambdas.api_gateway_function
      CodeUri: .
      Runtime: java11
      Architectures:
        - arm64
      MemorySize: 256
      Timeout: 10
      Layers:
        - !Ref JavaWrapperLayer
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/java-wrapper.sh
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: makefile

  JavaWrapperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: JavaWrapperLayer
      Description: Layer with Java Wrapper that adds Tiered compilation Java options.
      ContentUri: .
      CompatibleArchitectures:
        - x86_64
        - arm64
      CompatibleRuntimes:
        - java8
        - java11
    Metadata:
      BuildMethod: makefile

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: Prod

Outputs:
  ApiGatewayFunctionEndpoint:
    Description: Endpoint for ApiGatewayFunction
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello
